import type { Metadata } from 'next'
import './globals.css'
import NavBar from './components/nav-menu/navMenu'
import { MdOutlineInventory } from "react-icons/md";
import { LuLayoutDashboard } from "react-icons/lu";
import { PiFactory, PiWarehouse } from "react-icons/pi";
import { BsBoxArrowUpRight, BsBoxArrowInDownLeft, BsBoxes, BsPerson, BsPiggyBank } from "react-icons/bs";
import { HeaderBar } from './components/header-bar/header-bar'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const menuItems = [
  {
    icon: <LuLayoutDashboard />,
    label: 'Dashboard',
    href: '#'
  },
  {
    icon: <MdOutlineInventory />,
    label: "Inventory",
    href: "/inventory"
  },
  {
    label: "Items",
    icon: <BsBoxes />,
    href: "#"
  },
  {
    label: "Purchase Orders",
    icon: <BsBoxArrowInDownLeft />,
    href: "#"
  },
  {
    label: 'Sell Orders',
    icon: <BsBoxArrowUpRight />,
    href: "#"
  },
  {
    label: 'Providers',
    icon: <PiFactory />,
    href: "#"
  },
  {
    label: 'Customers',
    icon: <BsPerson />,
    href: "#"
  },
  {
    label: 'Warehouses',
    icon: <PiWarehouse />,
    href: "#"
  },
  {
    label: 'Banks',
    icon: <BsPiggyBank />,
    href: "#"
  }
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <div className="flex w-full h-full">
            <NavBar>{menuItems}</NavBar>
            <div className="bg-[#0e0e0e] bg-opacity-90 w-[100%]">
              <HeaderBar />
              {children}
            </div>
          </div>
      </body>
    </html>
  )
}
